# version: 2.1

# workflows:
#   version: 2
#   build:
#     jobs:
#       - build

# jobs:
#   build:
#     working_directory: ~/teamwork
#     docker:
#       - image: circleci/node:4.8.2 # Primary execution image
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#       - image: circleci/postgres:9.6-alpine        # Service/dependency image
#         auth:
#           username: mydockerhub-user
#           password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
#         environment:
#           PG_HOST: localhost
#           POSTGRES_USER: postgres
#           POSTGRES_DB: teamwork_test
#     steps:
#       - checkout
#       - run:
#           name: update-npm
#           command: 'sudo npm install -g npm@5'
#       - restore_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#       - run:
#           name: install-npm-wee
#           command: npm install
#       - save_cache:
#           key: dependency-cache-{{ checksum "package-lock.json" }}
#           paths:
#             - ./node_modules
#       - run:
#           name: test
#           command: npm test
#       environment:
#           DATABASE_URL: "postgres://ubuntu@localhost:5432/db_name"

version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
      - image: circleci/postgres:9.6-alpine  
        environment:
           SALT: process.env.SALT
           PORT: process.env.PORT
           SECRET_KEY: process.env.SECRET_KEY
           PG_HOST: localhost
           POSTGRES_USER: postgres
           POSTGRES_PASS: Kehinde
           POSTGRES_DB: process.env.TEST_DATABASE_URL
           CLOUDINARY_CLOUD_NAME: process.env.CLOUDINARY_CLOUD_NAME
           CLOUDINARY_API_KEY: process.env.CLOUDINARY_API_KEY
           CLOUDINARY_API_SECRET: process.env.CLOUDINARY_API_SECRET
           PASSWORD: process.env.PASSWORSD

    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
      - run: npm install

      - save_cache:
         key: dependency-cache-{{ checksum "package-lock.json" }}
         paths:
             - ./node_modules     
      - run: npm test
        environment:
          DATABASE_URL=postgres://postgres:Kehinde@127.0.0.1:5432/teamwork_db
